### ISSUE TITLE
ruby-capstone 

### ISSUE THREAD

**Issue by AlaaShaheen2** [AlaaShaheen2/ruby-capstone#5]
This is the link for the project cards 👍 
[Project](https://github.com/AlaaShaheen2/ruby-capstone/projects/1)

We are two code partners 👍 
1) Alaa Shaheen
2) Mulugeta Belete
 
Tasks listed for Alaa Shaheen: Team member #1 

Tasks listed for Mulugeta Belete: Team member #2 

Tasks listed for both of us: Team member #3

**Comment by omarsalem7** [comment]
Hi team 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Kanban board project created ✔️

## Required Changes ♻️

- [ ] Kindly add cards for your project tasks and divide them between your team members equally. Also consider adding titles, descriptions, number of points, and assigned team member.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by belmeetmule** [comment]
Dear Reviewer, 

##Project link
This is the link for the project cards 👍
[Project](https://github.com/AlaaShaheen2/ruby-capstone/projects/1)

##Team members
We are two code partners 👍

- [ ] Alaa Shaheen  (Team member #1 )
- [ ] Mulugeta Belete (Team member #2)

**Comment by Reem-lab** [comment]
# Hi Team , 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights
- Great working on the set up the kanban board and assigning the tasks between you🔥🚀🎉

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
